### ISSUE TITLE
[CORE] CI Skipping

### ISSUE THREAD

**Issue by filipdutescu** [cookiejar/cookietemple#224]
**Associated Template/Command/Core**
Feature request is associated with the core of COOKIETEMPLE, both it and its templates could benefit  from it.

**Is your feature request related to a problem? Please describe.**
Lack of an option to skip CI workflows on commit messages could lead to rapid consumption of all minutes offered by GitHub for a free account/repository. The option to skip on commit CI would help resolve the issue, as well as speed up the dev process (since you do not need to wait for the result).

**Describe the solution you'd like**
The solution I propose is one I used in [my C++ template](https://github.com/filipdutescu/modern-cpp-template), as described in [this feature request](https://github.com/filipdutescu/modern-cpp-template/issues/3). To summarize, I suggest the usage of a specific "flag", such as `[skip ci]`/`[ci skip]` in the commit message, which would prompt GH Actions not to run for that commit.

An example of generating a CI skippable commit:
````bash
git commit -m "my normal commit message [skip ci]"
````

**Describe alternatives you've considered**
Alternatives to the proposed feature are:
  * A **blacklist** containing files that, if changed, *would not* trigger the workflows,
  * A **whitelist** containing files that, if changed, *would* trigger the workflows,
  * Changing the trigger from *on push* to *manual*

**Additional context**
An example of how to implement it is by adding in the job the following conditional:
````yaml
jobs:
  build:  # assuming it is the job you want to skip

    runs-on: ubuntu-latest  # desired OS
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
````
