### ISSUE TITLE
bandit in cli-python workflow is CT stuff

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#351]
Should be more like:

```
name: Run bandit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit
        run: bandit -r {{ cookiecutter.project_slug }} -c .bandit.yml
```
