### ISSUE TITLE
Add pre-commit hooks like autopep8

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#505]
Before a commit autopep8 should run.

Example

Add .pre-commit-config.yaml

```
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
      - id: isort
        types: [python]
        args:
          - "--multi-line=3"
          - "--trailing-comma"
          - "--force-grid-wrap=0"
          - "--use-parentheses"
          - "--line-width=88"

  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args:
          - "--make-summary-multi-line"
          - "--pre-summary-newline"
          - "--in-place"
          - "--recursive"

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        exclude: (megaqc/templates|megaqc/static)

```

https://github.com/pre-commit/mirrors-autopep8
