### ISSUE TITLE
Check whether we can remove the requirements.txt file from the docs

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#834]
```
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
    configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
    version: 3.8
    install:
        - method: pip
          path: .
        - requirements: docs/requirements.txt
```

All documentation requirements should be in the pyproject.toml file. Hence, the `pip install .` should hopefully include all requirements to build the docs.
I'd remove the documentation requirements.txt if this is the case.
