### ISSUE TITLE
Missing isort configuration to work with black.

### ISSUE THREAD

**Issue by picciama** [cookiejar/cookietemple#897]
**Associated Template/Command/Core**

cookietemple create -> cli -> python

**Describe the bug**

When running the pre-commit hooks, isort may conflict with black. The problem is that isort sometimes reorders differently than black. This leads to failure of the pre-commit test because the change that is made by black is immediately reversed by isort.
In the end, no file has been changed but the test thinks it failed.
This behaviour can be circumvented by forcing isort to be cautious about changes made by black.
One can add `--profile black`.
This could either be done in `.pre-commit-config.yaml`:
```
repos:
     ...
     - repo: https://github.com/pycqa/isort
       rev: 5.8.0
       hooks:
          - id: isort
            name: isort (python)
            args: ["--profile", "black"]  # new code
     ...

```

or adding this to `pyproject.toml` in the default TEMPLATE:
```
[tool.isort]
profile = "black"
```

Further information: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html

**To Reproduce**

Not sure how to reproduce it exactly as I cannot remember what caused the conflict in my case.
But this issue provides an example: https://github.com/PyCQA/isort/issues/1518

**Expected behavior**

Black and isort should both agree and agree at all times when executing the pre-commit hooks.

**System [please complete the following information]:**

-   OS: Debian 11
-   Python: 3.8 / 3.9 
-   Virtual environment: conda
-   cookietemple: 1.3.11

**Additional context**

---
