### ISSUE TITLE
Do not bump patch versions with dependabot

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#928]
```
    ignore:
      # Official actions have moving tags like v1
      - dependency-name: "pip/*"
        update-types: ["version-update:semver-patch"]
```

This is actually possible!
